"""把 10 份 AI 复核结果整理成 eval_ai_review.json 供 run_eval.py 读取。

agent 输出含零宽字符、末尾多余引号等,这里统一清洗。
"""

import json
import re
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent

# 10 份 AI 复核原始输出（来自 Explore agent，已粘贴）
RAW = [
    r'''{"doc_id":"603160_汇顶科技_2021年报","fields":{"rd_expense_total":{"gold":198221.58,"is_correct":false,"evidence_correct":false,"override_error":"section_error","notes":"研发投入合计1,982,215,830.15元=198,221.58万元，模型漏抽"},"rd_capitalized_amount":{"gold":29022.17,"is_correct":true,"evidence_correct":true,"override_error":"","notes":"本期资本化研发投入290,221,665.17元=29,022.17万元"},"rd_expensed_amount":{"gold":169199.42,"is_correct":false,"evidence_correct":false,"override_error":"section_error","notes":"本期费用化研发投入1,691,994,164.98元=169,199.42万元，模型漏抽"},"dev_cost_opening":{"gold":0,"is_correct":true,"evidence_correct":true,"override_error":"","notes":"开发支出期初余额为空即0"},"dev_cost_closing":{"gold":29022.17,"is_correct":true,"evidence_correct":true,"override_error":"","notes":"开发支出期末余额290,221,665.17元=29,022.17万元"},"impairment":{"gold":null,"is_correct":null,"evidence_correct":false,"override_error":"","notes":"开发支出附注无减值列"},"capitalization_rate":{"gold":14.64,"is_correct":false,"evidence_correct":false,"override_error":"section_error","notes":"资本化比重14.64%，模型漏抽"},"capitalization_condition":{"gold":"内部研究开发项目开发阶段的支出，同时满足下列条件时确认为无形资产：（1）完成该无形资产以使其能够使用或出售在技术上具有可行性；（2）具有完成该无形资产并使用或出售的意图；（3）无形资产产生经济利益的方式；（4）有足够的技术、财务资源和其他资源支持；（5）归属于该无形资产开发阶段的支出能够可靠地计量。","is_correct":true,"evidence_correct":true,"override_error":"","notes":"模型抽取与原文一致"}}}''',
    r'''{"doc_id":"603160_汇顶科技_2022年报","fields":{"rd_expense_total":{"gold":193333.74,"is_correct":false,"evidence_correct":false,"override_error":"section_error","notes":"研发投入合计1,933,337,445.03元(193333.74万元)明确披露，模型未抽取"},"rd_capitalized_amount":{"gold":48580.84,"is_correct":false,"evidence_correct":false,"override_error":"data_error","notes":"本期资本化485,808,380.07元(48580.84万元)，模型误取开发支出期初余额29022.17"},"rd_expensed_amount":{"gold":144752.91,"is_correct":false,"evidence_correct":false,"override_error":"section_error","notes":"本期费用化1,447,529,064.96元(144752.91万元)明确披露，模型未抽取"},"dev_cost_opening":{"gold":29022.17,"is_correct":false,"evidence_correct":false,"override_error":"data_error","notes":"开发支出期初余额290,221,665.17元(29022.17万元)，模型误填0.0"},"dev_cost_closing":{"gold":58271.13,"is_correct":false,"evidence_correct":false,"override_error":"data_error","notes":"开发支出期末余额582,711,337.36元(58271.13万元)，模型误填期初余额29022.17"},"impairment":{"gold":null,"is_correct":true,"evidence_correct":true,"override_error":"","notes":"开发支出附注无减值准备列，模型正确返回null"},"capitalization_rate":{"gold":25.13,"is_correct":false,"evidence_correct":false,"override_error":"section_error","notes":"资本化比重25.13%明确披露，模型未抽取"},"capitalization_condition":{"gold":"内部研究开发项目开发阶段的支出，同时满足下列条件时确认为无形资产：(1)完成该无形资产以使其能够使用或出售在技术上具有可行性；(2)具有完成该无形资产并使用或出售的意图；(3)无形资产产生经济利益的方式；(4)有足够的技术、财务资源和其他资源支持；(5)归属于该无形资产开发阶段的支出能够可靠地计量。","is_correct":true,"evidence_correct":true,"override_error":"","notes":"匹配附注原文"}}}''',
    r'''{"doc_id":"000725_京东方A_2022年报","fields":{"rd_expense_total":{"gold":1260188.05,"is_correct":true,"evidence_correct":true,"override_error":"","notes":"研发投入金额12,601,880,481元换算万元"},"rd_capitalized_amount":{"gold":203626.43,"is_correct":true,"evidence_correct":true,"override_error":"","notes":"研发投入资本化的金额2,036,264,271元换算万元"},"rd_expensed_amount":{"gold":1056561.62,"is_correct":true,"evidence_correct":true,"override_error":"","notes":"总额减资本化金额计算"},"dev_cost_opening":{"gold":null,"is_correct":null,"evidence_correct":false,"override_error":"","notes":"年报未单独披露开发支出期初余额"},"dev_cost_closing":{"gold":null,"is_correct":null,"evidence_correct":false,"override_error":"","notes":"年报未单独披露开发支出期末余额"},"impairment":{"gold":null,"is_correct":null,"evidence_correct":false,"override_error":"","notes":"资产减值损失附注无开发支出减值项"},"capitalization_rate":{"gold":16.16,"is_correct":true,"evidence_correct":true,"override_error":"","notes":"资本化研发投入占研发投入的比例16.16%"},"capitalization_condition":{"gold":"研究阶段的支出，于发生时计入当期损益。开发阶段的支出，如果开发形成的某项产品或工序等在技术和商业上可行，而且本集团有充足的资源和意向完成开发工作，并且开发阶段支出能够可靠计量，则开发阶段的支出便会予以资本化。","is_correct":false,"evidence_correct":false,"override_error":"parse_error","notes":"模型输出占位符(文本)而非资本化条件原文"}}}''',
    r'''{"doc_id":"000725_京东方A_2023年报","fields":{"rd_expense_total":{"gold":1256335.27,"is_correct":true,"evidence_correct":true,"override_error":"","notes":"研发投入金额换算万元"},"rd_capitalized_amount":{"gold":209954.66,"is_correct":true,"evidence_correct":true,"override_error":"","notes":"研发投入资本化的金额换算万元"},"rd_expensed_amount":{"gold":1046380.61,"is_correct":true,"evidence_correct":true,"override_error":"","notes":"总额减资本化计算"},"dev_cost_opening":{"gold":0,"is_correct":false,"evidence_correct":false,"override_error":"section_error","notes":"开发支出附注年初余额为空即0;模型误报null"},"dev_cost_closing":{"gold":16697.75,"is_correct":false,"evidence_correct":false,"override_error":"section_error","notes":"开发支出年末余额166,977,531元=16,697.75万元;模型误报null"},"impairment":{"gold":0,"is_correct":false,"evidence_correct":false,"override_error":"section_error","notes":"开发支出附注无减值列,减值为0;模型误报null"},"capitalization_rate":{"gold":16.71,"is_correct":true,"evidence_correct":true,"override_error":"","notes":"资本化研发投入占研发投入的比例16.71%"},"capitalization_condition":{"gold":"研究阶段的支出，于发生时计入当期损益。开发阶段的支出，如果开发形成的某项产品或工序等在技术和商业上可行，而且本集团有充足的资源和意向完成开发工作，并且开发阶段支出能够可靠计量，则开发阶段的支出便会予以资本化。","is_correct":false,"evidence_correct":false,"override_error":"hallucination","notes":"模型输出占位符(文本)而非原文"}}}''',
    r'''{"doc_id":"000963_华东医药_2022年报","fields":{"rd_expense_total":{"gold":119630.95,"is_correct":true,"evidence_correct":true,"override_error":"","notes":"研发投入金额一致"},"rd_capitalized_amount":{"gold":22779.44,"is_correct":true,"evidence_correct":true,"override_error":"","notes":"研发投入资本化金额一致"},"rd_expensed_amount":{"gold":96851.51,"is_correct":true,"evidence_correct":true,"override_error":"","notes":"总额减资本化,会计恒等式成立"},"dev_cost_opening":{"gold":0,"is_correct":false,"evidence_correct":false,"override_error":"section_error","notes":"开发支出附注期初余额合计为空即0,模型漏取"},"dev_cost_closing":{"gold":64135.46,"is_correct":false,"evidence_correct":false,"override_error":"section_error","notes":"开发支出期末余额641,354,586.80元=64135.46万元,模型漏取"},"impairment":{"gold":0,"is_correct":false,"evidence_correct":false,"override_error":"section_error","notes":"开发支出本期减少列均为空,无减值,模型漏取报null"},"capitalization_rate":{"gold":19.04,"is_correct":true,"evidence_correct":true,"override_error":"","notes":"资本化率19.04%一致"},"capitalization_condition":{"gold":"内部研究开发项目开发阶段的支出,同时满足下列条件的,确认为无形资产:(1)完成该无形资产以使其能够使用或出售在技术上具有可行性;(2)具有完成该无形资产并使用或出售的意图;(3)无形资产产生经济利益的方式;(4)有足够的技术、财务资源和其他资源支持;(5)归属于该无形资产开发阶段的支出能够可靠地计量","is_correct":false,"evidence_correct":false,"override_error":"hallucination","notes":"模型输出占位符(文本)未提供资本化条件原文"}}}''',
    r'''{"doc_id":"002008_大族激光_2021年报","fields":{"rd_expense_total":{"gold":143622.95,"is_correct":false,"evidence_correct":false,"override_error":"hallucination","notes":"研发投入金额1,436,229,475.98元=143622.95万元，模型148617.78不匹配"},"rd_capitalized_amount":{"gold":4177.64,"is_correct":false,"evidence_correct":false,"override_error":"hallucination","notes":"研发投入资本化金额41,776,438.18元=4177.64万元，模型14054.41错误"},"rd_expensed_amount":{"gold":139445.30,"is_correct":false,"evidence_correct":false,"override_error":"hallucination","notes":"总额减资本化=139445.30万元，模型134563.37错误"},"dev_cost_opening":{"gold":10540.73,"is_correct":false,"evidence_correct":false,"override_error":"hallucination","notes":"开发支出期初余额105,407,339.68元=10540.73万元，模型14447.75错误"},"dev_cost_closing":{"gold":3932.46,"is_correct":false,"evidence_correct":false,"override_error":"hallucination","notes":"开发支出期末余额39,324,629.07元=3932.46万元，模型25297.82错误"},"impairment":{"gold":null,"is_correct":true,"evidence_correct":true,"override_error":"","notes":"开发支出表无减值列，模型亦为null"},"capitalization_rate":{"gold":2.91,"is_correct":false,"evidence_correct":false,"override_error":"hallucination","notes":"资本化率2.91%，模型9.46%系由错误基数计算"},"capitalization_condition":{"gold":"开发阶段的支出同时满足下列条件时，才能确认为无形资产：A.完成该无形资产以使其能够使用或出售在技术上具有可行性；B.具有完成该无形资产并使用或出售的意图；C.无形资产产生经济利益的方式；D.有足够的技术、财务资源和其他资源支持；E.归属于该无形资产开发阶段的支出能够可靠地计量。","is_correct":false,"evidence_correct":false,"override_error":"parse_error","notes":"模型仅输出占位符(文本)未抽取原文"}}}''',
    r'''{"doc_id":"002049_紫光国微_2023年报","fields":{"rd_expense_total":{"gold":163285.23,"is_correct":true,"evidence_correct":true,"override_error":"","notes":"研发投入金额换算万元,预测正确"},"rd_capitalized_amount":{"gold":7755.13,"is_correct":true,"evidence_correct":true,"override_error":"","notes":"研发投入资本化的金额换算万元,预测正确"},"rd_expensed_amount":{"gold":155530.11,"is_correct":true,"evidence_correct":true,"override_error":"","notes":"费用化研发支出换算万元,预测正确"},"dev_cost_opening":{"gold":420.54,"is_correct":false,"evidence_correct":false,"override_error":"parse_error","notes":"开发支出期初余额4,205,417.24元=420.54万元,模型误判null"},"dev_cost_closing":{"gold":7755.13,"is_correct":false,"evidence_correct":false,"override_error":"parse_error","notes":"开发支出期末余额77,551,274.83元=7755.13万元,模型误判null"},"impairment":{"gold":null,"is_correct":null,"evidence_correct":true,"override_error":"","notes":"研发支出附注无减值列,null正确"},"capitalization_rate":{"gold":4.75,"is_correct":true,"evidence_correct":true,"override_error":"","notes":"资本化率4.75%,预测正确"},"capitalization_condition":{"gold":"①完成该无形资产以使其能够使用或出售在技术上具有可行性；②具有完成该无形资产并使用或出售的意图；③经过公司内部可行性论证，极大可能以新产品、新应用模式等方式产生经济效益；④有足够的技术、低成本财务资源和其他资源支持；⑤归属于该无形资产开发阶段的支出能够可靠地计量。","is_correct":false,"evidence_correct":false,"override_error":"hallucination","notes":"模型输出占位符(文本)而非实际内容"}}}''',
    r'''{"doc_id":"603019_中科曙光_2022年报","fields":{"rd_expense_total":{"gold":247231.42,"is_correct":false,"evidence_correct":true,"override_error":"section_error","notes":"研发投入合计2,472,314,244.52元,模型170965.0万元与原文不符"},"rd_capitalized_amount":{"gold":152077.15,"is_correct":false,"evidence_correct":true,"override_error":"section_error","notes":"本期资本化1,520,771,473.61元(占比61.51%),模型误判null"},"rd_expensed_amount":{"gold":95154.28,"is_correct":false,"evidence_correct":true,"override_error":"section_error","notes":"本期费用化951,542,770.91元,模型误填为170965.0"},"dev_cost_opening":{"gold":55544.91,"is_correct":false,"evidence_correct":true,"override_error":"section_error","notes":"开发支出期初余额555,449,115.66元"},"dev_cost_closing":{"gold":163720.40,"is_correct":false,"evidence_correct":true,"override_error":"section_error","notes":"开发支出期末余额1,637,204,007.12元"},"impairment":{"gold":null,"is_correct":null,"evidence_correct":false,"override_error":"","notes":"开发支出附注减值列未单独列示"},"capitalization_rate":{"gold":61.51,"is_correct":false,"evidence_correct":true,"override_error":"section_error","notes":"资本化率61.51%"},"capitalization_condition":{"gold":"开发阶段的支出同时满足下列条件的，确认为无形资产：①完成该无形资产以使其能够使用或出售在技术上具有可行性；②具有完成该无形资产并使用或出售的意图；③无形资产产生经济利益的方式；④有足够的技术、财务资源和其他资源支持；⑤归属于该无形资产开发阶段的支出能够可靠地计量。","is_correct":false,"evidence_correct":true,"override_error":"parse_error","notes":"模型仅输出占位符(文本)"}}}''',
    r'''{"doc_id":"603501_韦尔股份_2021年报","fields":{"rd_expense_total":{"gold":261979.29,"is_correct":false,"evidence_correct":false,"override_error":"hallucination","notes":"研发投入合计2,619,792,931.95元=261,979.29万元,模型值174,017.66万元在全文无匹配"},"rd_capitalized_amount":{"gold":50957.48,"is_correct":false,"evidence_correct":false,"override_error":"section_error","notes":"研发投入情况表本期资本化509,574,824.09元=50,957.48万元,模型漏抽返回null"},"rd_expensed_amount":{"gold":211021.81,"is_correct":false,"evidence_correct":false,"override_error":"hallucination","notes":"本期费用化2,110,218,107.86元=211,021.81万元,模型值174,017.66万元全文无匹配"},"dev_cost_opening":{"gold":48083.14,"is_correct":false,"evidence_correct":false,"override_error":"section_error","notes":"开发支出附注期初余额480,831,412.00元=48,083.14万元,模型漏抽"},"dev_cost_closing":{"gold":67814.74,"is_correct":false,"evidence_correct":false,"override_error":"section_error","notes":"开发支出期末余额678,147,370.19元=67,814.74万元,模型漏抽"},"impairment":{"gold":null,"is_correct":null,"evidence_correct":true,"override_error":"","notes":"开发支出附注无减值列"},"capitalization_rate":{"gold":19.45,"is_correct":false,"evidence_correct":false,"override_error":"section_error","notes":"资本化率19.45%,模型漏抽返回null"},"capitalization_condition":{"gold":"内部研究开发项目开发阶段的支出，同时满足下列条件时确认为无形资产：（1）完成该无形资产以使其能够使用或出售在技术上具有可行性；（2）具有完成该无形资产并使用或出售的意图；（3）无形资产产生经济利益的方式；（4）有足够的技术、财务资源和其他资源支持；（5）归属于该无形资产开发阶段的支出能够可靠地计量。","is_correct":false,"evidence_correct":false,"override_error":"prompt_error","notes":"模型输出占位符(文本)而非实际内容"}}}''',
    r'''{"doc_id":"603501_韦尔股份_2022年报","fields":{"rd_expense_total":{"gold":321770.72,"is_correct":false,"evidence_correct":false,"override_error":"hallucination","notes":"研发投入合计3,217,707,152.17元=321770.72万元;模型253755.86万元与原文任何数字均不匹配"},"rd_capitalized_amount":{"gold":72212.03,"is_correct":false,"evidence_correct":false,"override_error":"section_error","notes":"研发投入情况表本期资本化722,120,288.13元=72212.03万元,模型漏填该表"},"rd_expensed_amount":{"gold":249558.69,"is_correct":false,"evidence_correct":false,"override_error":"hallucination","notes":"本期费用化2,495,586,864.04元=249558.69万元;模型253755.86万元不符"},"dev_cost_opening":{"gold":67814.74,"is_correct":false,"evidence_correct":false,"override_error":"section_error","notes":"开发支出附注期初余额678,147,370.19元=67814.74万元,模型未抽取"},"dev_cost_closing":{"gold":81056.41,"is_correct":false,"evidence_correct":false,"override_error":"section_error","notes":"开发支出期末余额810,564,075.58元=81056.41万元,模型未抽取"},"impairment":{"gold":null,"is_correct":true,"evidence_correct":true,"override_error":"","notes":"开发支出附注无减值列,gold为null与模型一致"},"capitalization_rate":{"gold":22.44,"is_correct":false,"evidence_correct":false,"override_error":"section_error","notes":"资本化率22.44%,模型漏填"},"capitalization_condition":{"gold":"研究阶段的支出，于发生时计入当期损益。开发阶段的支出同时满足下列条件的，确认为无形资产：（1）完成该无形资产以使其能够使用或出售在技术上具有可行性；（2）具有完成该无形资产并使用或出售的意图；（3）无形资产产生经济利益的方式；（4）有足够的技术、财务资源和其他资源支持；（5）归属于该无形资产开发阶段的支出能够可靠地计量。","is_correct":false,"evidence_correct":false,"override_error":"parse_error","notes":"附注披露5条资本化条件原文;模型返回占位符(文本)"}}}''',
]


def clean(s: str) -> str:
    # 去零宽字符、不可见控制符
    s = re.sub(r"[​‌‍﻿]", "", s)
    # 去末尾多余的单/双引号
    s = s.strip().strip("'").strip('"')
    # 截取第一个完整 JSON 对象
    start = s.find("{")
    end = s.rfind("}")
    if start >= 0 and end > start:
        s = s[start : end + 1]
    return s


def main() -> int:
    out: dict[str, dict] = {}
    for raw in RAW:
        obj = json.loads(clean(raw))
        doc_id = obj["doc_id"]
        fields = obj["fields"]
        # 转成 run_eval.py 期望的格式：field -> {is_correct, evidence_correct, override_error, notes, gold_value}
        converted: dict[str, dict] = {}
        for fname, fv in fields.items():
            converted[fname] = {
                "is_correct": bool(fv.get("is_correct")) if fv.get("is_correct") is not None else None,
                "evidence_correct": bool(fv.get("evidence_correct")),
                "override_error": fv.get("override_error", "") or "",
                "notes": fv.get("notes", ""),
                "gold_value": fv.get("gold"),
            }
        out[doc_id] = converted
    path = PROJECT_ROOT / "outputs" / "reports" / "eval_ai_review.json"
    path.write_text(json.dumps(out, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {len(out)} docs to {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
